[package]
name = "games"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
rand = "0.8.5"
serde = "1.0.203"
serde_json = "1.0.118"
serde_derive = "1.0.200"
crossterm= "0.27"
clap = { version = "4", features = ["derive"] }