[package]
name = "bmr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
